declare namespace InputModuleScssModule {
    export interface IInputModuleScss {
        'button-spacer-1': string;
        'button-spacer-2': string;
        'button-spacer-3': string;
        buttonSpacer1: string;
        buttonSpacer2: string;
        buttonSpacer3: string;
        'chevron-icon': string;
        'chevron-spacer': string;
        chevronIcon: string;
        chevronSpacer: string;
        'custom-padding-vertical': string;
        customPaddingVertical: string;
        'divider-line': string;
        dividerLine: string;
        'field-label': string;
        'field-label-icon-button': string;
        'field-label-wrapper': string;
        fieldLabel: string;
        fieldLabelIconButton: string;
        fieldLabelWrapper: string;
        'flex-structure-horizontal': string;
        'flex-structure-vertical': string;
        flexStructureHorizontal: string;
        flexStructureVertical: string;
        'full-height': string;
        fullHeight: string;
        icon: string;
        'icon-1-material': string;
        'icon-2-material': string;
        'icon-3-material': string;
        'icon-4-material': string;
        'icon-button': string;
        'icon-wrapper': string;
        icon1Material: string;
        icon2Material: string;
        icon3Material: string;
        icon4Material: string;
        iconButton: string;
        iconWrapper: string;
        'info-button-style': string;
        infoButtonStyle: string;
        'input-wrapper': string;
        inputWrapper: string;
        l: string;
        'left-icon': string;
        leftIcon: string;
        'logo-text': string;
        logoText: string;
        m: string;
        mappings: string;
        names: string;
        'octuple-menu': string;
        octupleMenu: string;
        'pill-shape': string;
        'pill-shape-with-icon': string;
        'pill-shape-with-icon-and-icon-button': string;
        'pill-shape-with-icon-button': string;
        'pill-shape-with-image-icon': string;
        pillShape: string;
        pillShapeWithIcon: string;
        pillShapeWithIconAndIconButton: string;
        pillShapeWithIconButton: string;
        pillShapeWithImageIcon: string;
        'right-icon': string;
        rightIcon: string;
        s: string;
        sourceRoot: string;
        sources: string;
        sourcesContent: string;
        'space-m': string;
        spaceM: string;
        spacer: string;
        'text-area': string;
        'text-area-no-expand': string;
        'text-area-resize-icon': string;
        'text-style': string;
        textArea: string;
        textAreaNoExpand: string;
        textAreaResizeIcon: string;
        textStyle: string;
        version: string;
        'with-icon': string;
        'with-icon-and-icon-button': string;
        'with-icon-button': string;
        'with-image-icon': string;
        withIcon: string;
        withIconAndIconButton: string;
        withIconButton: string;
        withImageIcon: string;
        xl: string;
        xxl: string;
        xxxl: string;
    }
}

declare const InputModuleScssModule: InputModuleScssModule.IInputModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InputModuleScssModule.IInputModuleScss;
};

export = InputModuleScssModule;
