declare namespace InputModuleScssModule {
    export interface IInputModuleScss {
        body1: string;
        body2: string;
        body3: string;
        button1: string;
        button2: string;
        button3: string;
        caption: string;
        'clear-icon-button': string;
        clearIconButton: string;
        dark: string;
        display1: string;
        display2: string;
        display3: string;
        display4: string;
        'field-label': string;
        'field-label-icon-button': string;
        fieldLabel: string;
        fieldLabelIconButton: string;
        header1: string;
        header2: string;
        header3: string;
        header4: string;
        header5: string;
        header6: string;
        'icon-button': string;
        'icon-material-l': string;
        'icon-material-m': string;
        'icon-material-s': string;
        'icon-material-xs': string;
        'icon-wrapper': string;
        iconButton: string;
        iconMaterialL: string;
        iconMaterialM: string;
        iconMaterialS: string;
        iconMaterialXs: string;
        iconWrapper: string;
        'info-button-style': string;
        infoButtonStyle: string;
        'input-stretch': string;
        'input-wrapper': string;
        inputStretch: string;
        inputWrapper: string;
        'label-icon-button': string;
        labelIconButton: string;
        'left-icon': string;
        leftIcon: string;
        mappings: string;
        names: string;
        'open-sans': string;
        openSans: string;
        'pill-shape': string;
        'pill-shape-with-icon': string;
        'pill-shape-with-icon-and-icon-button': string;
        'pill-shape-with-icon-button': string;
        'pill-shape-with-image-icon': string;
        pillShape: string;
        pillShapeWithIcon: string;
        pillShapeWithIconAndIconButton: string;
        pillShapeWithIconButton: string;
        pillShapeWithImageIcon: string;
        'pre-display': string;
        preDisplay: string;
        'right-icon': string;
        rightIcon: string;
        semibold: string;
        sourceRoot: string;
        sources: string;
        sourcesContent: string;
        subtitle1: string;
        subtitle2: string;
        'text-area': string;
        'text-area-no-expand': string;
        'text-area-resize-icon': string;
        'text-style': string;
        textArea: string;
        textAreaNoExpand: string;
        textAreaResizeIcon: string;
        textStyle: string;
        version: string;
        'with-icon': string;
        'with-icon-and-icon-button': string;
        'with-icon-button': string;
        'with-image-icon': string;
        withIcon: string;
        withIconAndIconButton: string;
        withIconButton: string;
        withImageIcon: string;
    }
}

declare const InputModuleScssModule: InputModuleScssModule.IInputModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InputModuleScssModule.IInputModuleScss;
};

export = InputModuleScssModule;
