declare namespace IconModuleScssModule {
    export interface IIconModuleScss {
        body1: string;
        body2: string;
        body3: string;
        'button-spacer-1': string;
        'button-spacer-2': string;
        'button-spacer-3': string;
        button1: string;
        button2: string;
        button3: string;
        buttonSpacer1: string;
        buttonSpacer2: string;
        buttonSpacer3: string;
        caption: string;
        'chevron-icon': string;
        'chevron-spacer': string;
        chevronIcon: string;
        chevronSpacer: string;
        'custom-padding-vertical': string;
        customPaddingVertical: string;
        display1: string;
        display2: string;
        display3: string;
        display4: string;
        'divider-line': string;
        dividerLine: string;
        'flex-structure-horizontal': string;
        'flex-structure-vertical': string;
        flexStructureHorizontal: string;
        flexStructureVertical: string;
        'full-height': string;
        fullHeight: string;
        header1: string;
        header2: string;
        header3: string;
        header4: string;
        header5: string;
        header6: string;
        icon: string;
        'icon-1-material': string;
        'icon-2-material': string;
        'icon-3-material': string;
        'icon-4-material': string;
        'icon-material-l': string;
        'icon-material-m': string;
        'icon-material-s': string;
        'icon-material-xs': string;
        icon1Material: string;
        icon2Material: string;
        icon3Material: string;
        icon4Material: string;
        iconMaterialL: string;
        iconMaterialM: string;
        iconMaterialS: string;
        iconMaterialXs: string;
        iconWrapper: string;
        l: string;
        'logo-text': string;
        logoText: string;
        m: string;
        mappings: string;
        names: string;
        'octuple-menu': string;
        octupleMenu: string;
        'open-sans': string;
        openSans: string;
        'pre-display': string;
        preDisplay: string;
        s: string;
        semibold: string;
        sourceRoot: string;
        sources: string;
        sourcesContent: string;
        'space-m': string;
        spaceM: string;
        spacer: string;
        subtitle1: string;
        subtitle2: string;
        version: string;
        xl: string;
        xxl: string;
        xxxl: string;
    }
}

declare const IconModuleScssModule: IconModuleScssModule.IIconModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IconModuleScssModule.IIconModuleScss;
};

export = IconModuleScssModule;
