name: Build

on:
  push:
    branches:
      - main
      - main-next
  pull_request:
    branches:
      - main
      - main-next

env:
  NODE_VERSION: 16.14.2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Load cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn test
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Load cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn build-storybook
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'EightfoldAI'
          destination-repository-name: 'octuple.github.io'
          user-email: ychhabra@eightfold.ai
          target-branch: main
      - run: yarn lint

