name: 'Chromatic'

on: push

env:
  NODE_VERSION: 16
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ env.NODE_VERSION }}
      - name: Load cached node_modules
        uses: actions/cache@v3
        run: yarn
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
