name: Octuple Publish Alerts

# Only trigger when the npm-publish workflow succeeded
on:
  workflow_run:
    workflows: [Publish Octuple]
    types:
      - completed

jobs:
  octuple-publish-alerts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        id: slack_md_converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ steps.changelog_reader.outputs.changes }}
      - name: Prepare slack message
        id: slack_prepare
        run: |
          CHANGE_LOG="${{ steps.slack_md_converter.outputs.text }}"
          CHANGE_LOG="$(echo "$CHANGE_LOG" | sed -z 's/\n/\\n/g')"
          echo "::set-output name=changelog::${CHANGE_LOG}"
      - name: Post to Slack channel
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "📦 Release ${{ steps.changelog_reader.outputs.version }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.slack_prepare.outputs.changelog }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " "
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "📦 Go to Release",
                        "emoji": true
                    },
                    "url": "https://github.com/EightfoldAI/octuple/releases/tag/v${{ steps.changelog_reader.outputs.version }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
